name: Simple SCP Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: create build directory
      run: |
        mkdir ../build
        cp -r . ../build
        tar -cvf build.tar ../build/
      
    - name: copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{  secrets.REMOTE_USER }}
        key: ${{  secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        rm: true
        source: "build.tar"
        target: "${{ secrets.REMOTE_DIR }}"
