name: Simple SCP Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{  secrets.REMOTE_USER }}
        key: ${{  secrets.SSH_KEY }}
        port: 22
        rm: true
        source: "index.html"
        target: "${{ secrets.REMOTE_DIR }}"
